# Generated by Django 3.2.7 on 2021-09-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.TextField(blank=True, max_length=200)),
                ('visited_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
