# Generated by Django 3.2.7 on 2021-09-10 14:18

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('page_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(choices=[('at_a_glance', 'At a Glance'), ('academics', 'Academics'), ('administration', 'Administration'), ('admission', 'Admission '), ('events', 'Events '), ('gallery', 'Gallery'), ('contact_us', 'None')], default='None', max_length=14)),
                ('page_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Static Pages Data',
            },
        ),
    ]
