# Generated by Django 3.2.7 on 2021-09-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=17)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/logo/')),
                ('header_title', models.CharField(max_length=256)),
                ('header_slogan', models.CharField(max_length=256)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(editable=False, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Header Information',
            },
        ),
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', models.ImageField(upload_to='images/slider')),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('slider_author', models.CharField(editable=False, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Add Slider Image',
            },
        ),
        migrations.CreateModel(
            name='SideBarBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='images/sidebar_banner')),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(editable=False, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Add Banner Image',
            },
        ),
        migrations.CreateModel(
            name='UsefulLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_title', models.CharField(max_length=256, null=True)),
                ('link_url', models.CharField(max_length=256)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('link_author', models.CharField(editable=False, max_length=100)),
            ],
        ),
    ]
