# Generated by Django 3.2.7 on 2021-09-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerinfo',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='images/favicon'),
        ),
    ]
