# Generated by Django 3.2.7 on 2021-09-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_headerinfo_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerinfo',
            name='header_title',
            field=models.ImageField(null=True, upload_to='images/header_title/'),
        ),
    ]
