# Generated by Django 3.2.7 on 2021-09-10 14:17

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_notice_title', models.CharField(max_length=256)),
                ('admission_notice_content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('admission_notice_author', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Admission Notice',
            },
        ),
        migrations.CreateModel(
            name='JobsBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=256)),
                ('job_content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('job_author', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Jobs Board',
            },
        ),
        migrations.CreateModel(
            name='NewsFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=256)),
                ('post_content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('post_thumbnail', models.ImageField(blank=True, upload_to='feeds/')),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('draft', 'Draft')], max_length=50)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('post_author', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Add New Post',
            },
        ),
        migrations.CreateModel(
            name='NoticeBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.CharField(max_length=256)),
                ('notice_content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('notice_author', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Notice Board',
            },
        ),
    ]
